language: python
python:
  - "2.7"
#  - "2.6"
#  - "3.3"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
env:
  - DJANGO_VERSION=1.8
  - DJANGO_VERSION=1.7
  - DJANGO_VERSION=1.6
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install .
  - pip install django==$DJANGO_VERSION
  - pip install coveralls
# # command to run tests, e.g. python setup.py test
script:
  - python setup.py develop
  - coverage run --rcfile='django_pluggableappsettings/tests/coverage.conf' --source='./django_pluggableappsettings/' django_pluggableappsettings/tests/travis_ci.py
after_success:
  - coveralls